<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','active-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('Talha_MediaTracking');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'talha_mediatracking_activities_tasks';
$coreDefs['tabs'][0]['link'] = 'talha_mediatracking_activities_tasks';
$coreDefs['tabs'][1]['link'] = 'talha_mediatracking_activities_tasks';
$viewdefs['Talha_MediaTracking']['base']['view']['active-tasks'] = $coreDefs;
