<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','history');
$coreDefs['dashlets'][0]['filter']['module'] = array('Talha_MediaTracking');
$coreDefs['tabs'][0]['link'] = 'talha_mediatracking_activities_meetings';
$coreDefs['tabs'][1]['link'] = 'talha_mediatracking_activities_emails';
$coreDefs['tabs'][2]['link'] = 'talha_mediatracking_activities_calls';
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'talha_mediatracking_activities_emails';
$viewdefs['Talha_MediaTracking']['base']['view']['history'] = $coreDefs;
