<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('Talha_MediaTracking');
$coreDefs['dashlets'][0]['config']['link'] = 'talha_mediatracking_activities_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'talha_mediatracking_activities_notes';
$viewdefs['Talha_MediaTracking']['base']['view']['attachments'] = $coreDefs;
